# Site settings
title: Pathfinder
description: > # this means to ignore newlines until "baseurl:"
  Site for path finder.

baseurl: "" # the subpath of your site, e.g. /blog/ 

# Build settings
markdown: kramdown
